---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-matches
  namespace: {{ .Release.Namespace }}
data:
  matches.rego: |
    package k8s
    import data.kubernetes

    matches[[kind, namespace, name, resource]] {
      resource := kubernetes[kind][namespace][name].object
    }

    matches[[kind, namespace, name, resource]] {
        resource := kubernetes[kind][namespace][name]
    }
  policy-matches.rego: | 
    package k8s
    import data.kubernetes.policies

    # Matches provides an abstraction to find policies that match the (name). 
    policymatches[[name, policy]] {
        policy := policies[name]
    }    