apiVersion: v1
kind: Service
metadata:
  name: mysvc1
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: myapp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: myapp
  type: LoadBalancer
 

